# Generated by Django 3.0.5 on 2020-04-21 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='phone number must be entered in the format: +84999999. Up to 14 digits allowed.', regex='^\\d{8,10}$')])),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='username')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('skills', models.CharField(max_length=1000, verbose_name='skill')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_login', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
