# Generated by Django 3.0.5 on 2020-04-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='full name'),
        ),
    ]
